"""create likes table

Revision ID: 047666c01e94
Revises: d19b4278a064
Create Date: 2021-01-10 20:33:15.847863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047666c01e94'
down_revision = 'd19b4278a064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('paletteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paletteId'], ['palettes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
